//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prolab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanıcı
    {
        public int kullanıcıid { get; set; }
        public int bookid { get; set; }
        public int kitapid { get; set; }
        public System.DateTime retundate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
